### ISSUE TITLE
axes incompatibility

### ISSUE THREAD

**Issue by Asmodasis** [robowork/robotics_tutorials#1]
Line 601 in Transformation.py requires the change to keyword 'auto' instead of 'equal'

**Comment by papachric** [comment]
'auto' will axes based on the aspect ration of the window, so they will appear out of proportion to each other
'equal' ensures that all axes are scaled the same so all unit vectors remain in proportion to each other regardless of window aspect ratio.

what is exactly the "incompatibility" issue you're encountering running this?

**Comment by Asmodasis** [comment]
Python just says "equal doesn't exist, did you mean auto?" I installed qt4
on python 3.

**Comment by papachric** [comment]
What's your matplotlib version? It seems like there's a big discussion where they recently discovered 'equal' is being misused and might have deprecated it. Can you try to see if
`self.axes.set_aspect(aspect=1)`
works? It's supposed to be the equivalent of 'equal'

**Comment by Asmodasis** [comment]
>>> import matplotlib
>>> print(matplotlib.__version__)
3.3.4

I tried to use self.axes.set_aspect(aspect=1) but all it said was:
$ python3 Transformations.py
  File "Transformations.py", line 604
    self.axes.set_aspect(aspect = 1)
                                   ^
TabError: inconsistent use of tabs and spaces in indentation
However, self.axes.set_aspect('auto') seemed to work and I get this.

[image: Screenshot from 2022-10-06 16-21-11.png]

   Thank you for the help, this isn't entirely needed for the homework (we
can take the snippets of code out) but I was just trying to get the whole
file working because why not.

    Shawn.

**Comment by papachric** [comment]
The error you mention here `TabError: inconsistent use of tabs and spaces in indentation` is a python syntax error, it has nothing to do with the set_aspect method itself.

Can you try to check for inconsistent indentation (mixing spaces/tabs) and rerun with `self.axes.set_aspect(aspect=1)` or just `self.axes.set_aspect(1)`

**Comment by Asmodasis** [comment]
oh I apologize I forgot linux codes tabs differently. This is what I get

$ python3 Transformations.py
/usr/local/lib/python3.6/dist-packages/matplotlib/backends/qt_editor/figureoptions.py:11:
MatplotlibDeprecationWarning:
The support for Qt4  was deprecated in Matplotlib 3.3 and will be removed
two minor releases later.
  from matplotlib.backends.qt_compat import QtGui
Transformations.py:10: MatplotlibDeprecationWarning:
The matplotlib.backends.backend_qt4agg backend was deprecated in Matplotlib
3.3 and will be removed two minor releases later.
  from matplotlib.backends.backend_qt4agg import FigureCanvasQTAgg as
FigureCanvas
Gtk-Message: 16:40:51.393: Failed to load module "canberra-gtk-module"
Traceback (most recent call last):
  File "Transformations.py", line 809, in <module>
    main()
  File "Transformations.py", line 804, in main
    form = AppForm()
  File "Transformations.py", line 67, in __init__
    self.create_main_frame()
  File "Transformations.py", line 604, in create_main_frame
    self.axes.set_aspect(aspect = 1)
  File
"/usr/local/lib/python3.6/dist-packages/mpl_toolkits/mplot3d/axes3d.py",
line 324, in set_aspect
    "Axes3D currently only supports the aspect argument "
NotImplementedError: Axes3D currently only supports the aspect argument
'auto'. You passed in 1.
